# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 394c129f731fa5b24f4ebec18e951a1eef83443aeaa85f1e41a02054f1637eb370bb2abdbc07611dacc13b6993e87b54a155cad6dce4e6dc7d09a0e001baf63f

test:
  secret_key_base: 929bf01977dff14cf7ee3590afd68da10e9d109a6c501e1a49b8b663b147b92fb2bee2a458939e3fa65a59255a3c755adcd57084fe29a5cf5fe8d46ab595da77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
